name: Build Android APK
run: |
    # 自动同意所有Android SDK协议
    yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
    buildozer android release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libsqlite3-dev libbz2-dev libffi-dev cmake python3-pip
          pip3 install buildozer

      - name: Build release APK
        run: buildozer android release

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}